import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navigation from "@/components/Navigation";
import { Footer } from "@/components/Footer";
import Providers from "@/components/Providers";
import { AuthProvider } from "./context/AuthContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <header>
            <Navigation />
          </header>
          <main
            className={`${geistSans.variable} ${geistMono.variable} min-h-extend-header-footer flex justify-center items-center bg-[#313492]`}
          >
            <Providers>{children}</Providers>
          </main>
          <footer className="flex items-center justify-center bg-gray-700 h-20">
            <Footer />
          </footer>
        </AuthProvider>
      </body>
    </html>
  );
}
